- name: Import maven installation tasks
  ansible.builtin.import_role:
    name: common
    tasks_from: maven

- name: install mysql
  ansible.builtin.dnf:
    name: mysql-server
    state: installed

- name: Load Schema
  ansible.builtin.shell: mysql -h mysql-dev.gdevops72.com -u{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-' ~ env ~ '/data/shipping:DB_USER', token=token, url='http://vault-internal.gdevops72.com:8200/') }} -p{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-' ~ env ~ '/data/shipping:DB_PASS', token=token, url='http://vault-internal.gdevops72.com:8200/') }} < /app/db/{{ item }}.sql
  loop:
    - schema
    - app-user
    - data

