- name: Copy dispatch service file
  ansible.builtin.copy:
    src: dispatch.service
    dest: /etc/systemd/system/dispatch.service

- name: Import golang installation tasks
  ansible.builtin.import_role:
    name: common
    tasks_from: golang


