- name: Copy MongoDB YUM repository file
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Import Node.js installation tasks
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs


