- name: Import Node.js installation tasks
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs

- name: Copy MongoDB YUM repository file
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install MongoDB Shell client (mongosh)
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: present

- name: Load Master Data into MongoDB
  ansible.builtin.shell: mongosh --host mongodb-dev.gdevops72.com </app/db/master-data.js

- name: Import SystemD service startup
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd