## 1. Setup NodeJS
#source common.sh
#component=catalogue
#NODEJS
#
#dnf install mongodb-mongosh -y
#mongosh --host mongodb-dev.gdevops72.com </app/db/master-data.js


- name: import nodejs
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs

- name: Copy mongodb repo file
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install MongoDB Shell client (mongosh)
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: present

- name: load data
  ansible.builtin.shell: mongosh --host mongodb-dev.gdevops72.com </app/db/master-data.js

