- name: Install maven
  ansible.builtin.dnf:
    name: maven
    state: installed

- name: Import App Prerequisites
  ansible.builtin.import_role:
    name: common
    tasks_from: app-prereq

- name: Rename application JAR file
  ansible.builtin.command:
    cmd: mv target/{{ component }}-1.0.jar {{ component }}.jar
    chdir: /app
    creates: /app/{{ component }}.jar

- name: Include systemd startup tasks
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd