- name: Copy component service file
  ansible.builtin.copy:
    src: "{{ component | default(role_name) }}.service"
    dest: "/etc/systemd/system/{{ component | default(role_name) }}.service"

- name: Start and enable service
  ansible.builtin.service:
    state: restarted
    enabled: true
    daemon_reload: true
    name: "{{ component | default(role_name) }}"